spring.application.name=Primeiro_Projeto_SpringBoot

spring.datasource.url=jdbc:mysql://localhost:3306/PrimeiroProjetoSpringBoot?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

springdoc.swagger-ui.path=/swagger

# nivel de log
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# pasta de logs
logging.file.path=logs

# arquivo principal
logging.file.name=logs/app.log